(function(){
  var s = document.createElement('style');
  s.id = 'qimam-patch-css';
  s.textContent = '@keyframes gscrRun{0%,8%{transform:translateY(0);animation-timing-function:cubic-bezier(.42,0,.32,1)}75%,79%{transform:translateY(var(--d));animation-timing-function:cubic-bezier(.5,0,.25,1)}100%{transform:translateY(0)}}.gscr-s img{animation-duration:24s!important}@keyframes qsRun{0%,8%{transform:translateY(0);animation-timing-function:cubic-bezier(.42,0,.32,1)}75%,79%{transform:translateY(var(--d));animation-timing-function:cubic-bezier(.5,0,.25,1)}100%{transform:translateY(0)}}.qs-t img{animation-duration:24s!important}#qimam-mockups{padding:88px 0 72px}#qimam-mockups .mk-inner{max-width:1360px;margin:0 auto;padding:0 28px}#qimam-mockups .mk-head{text-align:center;margin-bottom:60px}#qimam-mockups .mk-head h2{font-size:clamp(28px,4vw,46px);margin:0 0 14px}#qimam-mockups .mk-head p{opacity:.6;max-width:500px;margin:0 auto}#qimam-mockups .mk-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(360px,1fr));gap:32px}#qimam-mockups .mk-card{border-radius:18px;overflow:hidden;box-shadow:0 22px 64px -18px rgba(0,0,0,.55);transition:transform .38s,box-shadow .38s;background:#0a0a0a}#qimam-mockups .mk-card:hover{transform:translateY(-10px) scale(1.015)}#qimam-mockups .mk-card img{width:100%;height:auto;display:block}@media(max-width:768px){#qimam-mockups .mk-grid{grid-template-columns:1fr;gap:24px}}';
  document.head.appendChild(s);
  var MOCKS=[['01-safrat-albalad','صفرة البلد'],['02-sanad-law','سند للمحاماة'],['03-masar-alharamain','مسار الحرمين'],['04-tuwaiq-ai','تويق للذكاء الاصطناعي'],['05-rawashin','رواشين'],['06-rawa-real-estate','رواء العقارية'],['07-sadu-studio','استوديو السدو'],['08-sudair-energy','صدير للطاقة'],['09-darb-zubaydah','درب زبيدة'],['10-asala-fashion','اصالة للأزياء'],['11-alataa-charity','العطاء الخيرية'],['12-kunooz-heritage','كنوز التراث'],['13-alrowad-cafe','الرواد كافيه'],['14-nokhbat-alqowa','نخبة القوى'],['15-saudi-healthcare','الرعاية الصحية']];
  var BASE='https://qimampro.github.io/assets/mockups/';
  function buildSection(){var sec=document.createElement('section');sec.id='qimam-mockups';var cards=MOCKS.map(function(m){return '<div class="mk-card"><img src="'+BASE+m[0]+'.webp" alt="'+m[1]+'" loading="lazy" width="1448" height="1086"></div>';}).join('');sec.innerHTML='<div class="mk-inner"><div class="mk-head"><p class="eyebrow">معرض الاعمال</p><h2>نماذج مواقع قمم</h2><p>15 موقعا بهوية بصرية متكاملة</p></div><div class="mk-grid">'+cards+'</div></div>';return sec;}
  function inject(){var pkgs=document.getElementById('packages');if(pkgs)pkgs.parentNode.insertBefore(buildSection(),pkgs);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();var _t=setInterval(function(){var m=document.getElementById('qimam-mockups');if(m){if(!m.contains(s))m.appendChild(s);return}var p=document.getElementById('packages');if(p)p.parentNode.insertBefore(buildSection(),p)},300);setTimeout(function(){clearInterval(_t)},60000);
})();
